baseURL = "/"
languageCode = "sv"
title = "En hållbar plattform för säkra molntjänster"
author = "Safespring"
copyright = "2023 Safespring"

# Pagination
paginate = 10
paginatePath = "blog"

[params]
  mainSections = ['blogg', 'webinar', 'whitepaper', 'solution-brief']

[sitemap]
    changefreq = "daily"
    filename = "sitemap.xml"
    priority = 0.5

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'igor'
    tabWidth = 4
[markup.goldmark.renderer]
  hardWraps = false
  unsafe = true
  xhtml = false

[blackfriday]
fractions = false

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
